name: mtl-demo
version: 0.0.1.0

extra-source-files:
  - package.yaml

ghc-options: -Wall

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImpredicativeTypes
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NumericUnderscores
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances

library:
  dependencies:
    - base
    - exceptions
    - monad-control
    - monad-logger
    - mtl
    - persistent
    - persistent-sqlite
    - persistent-template
    - relude
    - resourcet
    - snap-core
    - text
    - transformers
    - transformers-base
    - unliftio
    - unliftio-core
  source-dirs: src

executables:
  hede:
    main: app/Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - relude
      - mtl-demo
      - snap-core
      - snap-server
